default:
  SECRET_KEY: 'z5um)_x-1!3d!2e6q4byfxnd@a530)o@sy)2zasc#z%_t3ul!9'
  DEBUG: True
  DATABASES:
    default:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'db.sqlite3'
  ALLOWED_HOSTS:
    - '127.0.0.1'
    - 'localhost'
    - 'testserver'
  INSTALLED_APPS:
    - 'readorganizer_api.apps.ReadOrganizerApiConfig'
    - 'corsheaders'
    - 'django.contrib.admin'
    - 'django.contrib.auth'
    - 'django.contrib.contenttypes'
    - 'django.contrib.sessions'
    - 'django.contrib.messages'
    - 'django.contrib.staticfiles'
    - 'django_extensions'
    - 'rest_framework.authtoken'
  MIDDLEWARE:
    - 'django.middleware.security.SecurityMiddleware'
    - 'django.contrib.sessions.middleware.SessionMiddleware'
    - 'corsheaders.middleware.CorsMiddleware'
    - 'django.middleware.common.CommonMiddleware'
    - 'django.middleware.csrf.CsrfViewMiddleware'
    - 'django.contrib.auth.middleware.AuthenticationMiddleware'
    - 'django.contrib.messages.middleware.MessageMiddleware'
    - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  ROOT_URLCONF: 'readorganizer.urls'
  TEMPLATES:
    - BACKEND: 'django.template.backends.django.DjangoTemplates'
      DIRS: []
      APP_DIRS: True
      OPTIONS:
        context_processors:
          - 'django.template.context_processors.debug'
          - 'django.template.context_processors.request'
          - 'django.contrib.auth.context_processors.auth'
          - 'django.contrib.messages.context_processors.messages'
  WSGI_APPLICATION: 'readorganizer.wsgi.application'
  AUTH_PASSWORD_VALIDATORS:
    - 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    - 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
    - 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
    - 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
  LANGUAGE_CODE: 'en-us'
  DEFAULT_AUTO_FIELD: 'django.db.models.BigAutoField'
  TIME_ZONE: 'UTC'
  USE_I18N: True
  USE_L10N: True
  USE_TZ: True
  STATIC_URL: '/static/'
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      - 'rest_framework.authentication.BasicAuthentication'
      - 'rest_framework.authentication.SessionAuthentication'
      - 'rest_framework.authentication.TokenAuthentication'
    TEST_REQUEST_DEFAULT_FORMAT: 'json'
  CORS_ALLOWED_ORIGINS:
    - 'http://127.0.0.1:8080'
    - 'http://localhost:8080'
    - 'http://testserver:8000'

production:
  DEBUG: False
