# Generated by Django 3.2.4 on 2021-09-23 19:06
from django.db import migrations

from readorganizer_api.constants import MANUAL_CHANNEL_ID
from readorganizer_api.enums import ChannelTypesEnum


def create_manual_channel(apps, schema_editor):
    Channel = apps.get_model("readorganizer_api", "Channel")
    channel = Channel(
        id=MANUAL_CHANNEL_ID,
        url="file:///var/run/shm/readorganizer/manual_channel",
        channel_type=ChannelTypesEnum.MANUAL,
        active=False,
    )
    channel.save()


class Migration(migrations.Migration):

    dependencies = [
        ("readorganizer_api", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_manual_channel)]
