default:
  SECRET_KEY: 'z5um)_x-1!3d!2e6q4byfxnd@a530)o@sy)2zasc#z%_t3ul!9'
  DEBUG: True
  DATABASES:
    default:
      ENGINE: 'django.db.backends.sqlite3'
      NAME: 'db.sqlite3'
  CACHES:
    default:
      BACKEND: 'django.core.cache.backends.db.DatabaseCache'
      LOCATION: 'django_cache'
  ALLOWED_HOSTS:
    - '127.0.0.1'
    - 'localhost'
    - 'testserver'
  INSTALLED_APPS:
    - 'corsheaders'
    - 'django.contrib.admin'
    - 'django.contrib.auth'
    - 'django.contrib.contenttypes'
    - 'django.contrib.sessions'
    - 'django.contrib.messages'
    - 'django.contrib.staticfiles'
    - 'django_extensions'
    - 'django_filters'
    - 'django_celery_beat'
    - 'django_celery_results'
    - 'rest_framework.authtoken'
    - 'taggit'
    - 'taggit_serializer'
    - 'kustosz'
  MIDDLEWARE:
    - 'django.middleware.security.SecurityMiddleware'
    - 'corsheaders.middleware.CorsMiddleware'
    - 'django.contrib.sessions.middleware.SessionMiddleware'
    - 'django.middleware.common.CommonMiddleware'
    - 'django.middleware.csrf.CsrfViewMiddleware'
    - 'django.contrib.auth.middleware.AuthenticationMiddleware'
    - 'django.contrib.messages.middleware.MessageMiddleware'
    - 'django.middleware.clickjacking.XFrameOptionsMiddleware'
  ROOT_URLCONF: 'kustosz.urls'
  TEMPLATES:
    - BACKEND: 'django.template.backends.django.DjangoTemplates'
      DIRS: []
      APP_DIRS: True
      OPTIONS:
        context_processors:
          - 'django.template.context_processors.debug'
          - 'django.template.context_processors.request'
          - 'django.contrib.auth.context_processors.auth'
          - 'django.contrib.messages.context_processors.messages'
  WSGI_APPLICATION: 'kustosz.wsgi.application'
  AUTH_PASSWORD_VALIDATORS:
    - 'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'
    - 'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'
    - 'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'
    - 'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'
  LANGUAGE_CODE: 'en-us'
  DEFAULT_AUTO_FIELD: 'django.db.models.BigAutoField'
  AUTH_USER_MODEL: 'kustosz.User'
  TIME_ZONE: 'UTC'
  USE_I18N: True
  USE_L10N: True
  USE_TZ: True
  LOGGING:
    version: 1
    disable_existing_loggers: False
    handlers:
      console:
        class: 'logging.StreamHandler'
      'null':
        class: 'logging.NullHandler'
    root:
      handlers:
        - 'console'
      level: 'WARNING'
    loggers:
      reader:
        handlers:
          - 'console'
        level: 'CRITICAL'
        propagate: False
      readability:
        handlers:
          - 'console'
        level: 'ERROR'
        propagate: False
  STATIC_URL: '/ui/'
  MEDIA_URL: '/media/'
  REST_FRAMEWORK:
    DEFAULT_AUTHENTICATION_CLASSES:
      - 'rest_framework.authentication.BasicAuthentication'
      - 'rest_framework.authentication.SessionAuthentication'
      - 'rest_framework.authentication.TokenAuthentication'
    DEFAULT_FILTER_BACKENDS:
      - 'django_filters.rest_framework.DjangoFilterBackend'
    DEFAULT_PAGINATION_CLASS: 'rest_framework.pagination.LimitOffsetPagination'
    PAGE_SIZE: 100
    TEST_REQUEST_DEFAULT_FORMAT: 'json'
  CORS_ALLOWED_ORIGINS:
    - 'http://127.0.0.1:8080'
    - 'http://localhost:8080'
    - 'http://testserver:8000'
    - 'http://127.0.0.1:80'
    - 'http://localhost:80'
    - 'http://127.0.0.1'
    - 'http://localhost'
  CELERY_BROKER_URL: "filesystem://"
  CELERY_BROKER_TRANSPORT_OPTIONS:
    data_folder_out: '.celery/queue'
    data_folder_in: '.celery/queue'
    store_processed: False
  CELERY_BEAT_SCHEDULER: 'django_celery_beat.schedulers:DatabaseScheduler'
  CELERY_RESULT_BACKEND: 'django-db'
  KUSTOSZ_DEDUPLICATE_DAYS: 2
  KUSTOSZ_FEED_READER_WORKERS: 10
  KUSTOSZ_FETCH_CHANNELS_CHUNK_SIZE: 50
  KUSTOSZ_FETCH_PAGE_MAX_RETRIES: 10
  KUSTOSZ_LOCK_EXPIRE: 180
  KUSTOSZ_PERIODIC_FETCH_NEW_CONTENT_INTERVAL: 5
  KUSTOSZ_READABILITY_NODE_ENABLED: False
  KUSTOSZ_READABILITY_NODE_EXECUTABLE: "kustosz-node-readability"
  KUSTOSZ_READABILITY_PYTHON_ENABLED: True
  KUSTOSZ_READING_SPEED_WPM: 230
  KUSTOSZ_REQUESTS_CACHE_INIT_OPTIONS:
    backend: 'filesystem'
    expire_after: 3600  # one hour, in seconds
  KUSTOSZ_URL_FETCHER_EXTRA_HEADERS: {}


production:
  DEBUG: False
