# SPDX-FileCopyrightText: 2022 Mirek Długosz <mirek@mirekdlugosz.com>
#
# SPDX-License-Identifier: CC0-1.0

name: CD
on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'
env:
  CHANGELOG_PATH: "${{ github.workspace }}-CHANGELOG.txt"
  POETRY_VERSION: "1.1.12"
  # If it's good enough for nox, it's good enough for us
  FORCE_COLOR: "1"
  # See https://github.com/theacodes/nox/issues/545
  # and https://github.com/pre-commit/pre-commit/issues/2178#issuecomment-1002163763
  SETUPTOOLS_USE_DISTUTILS: "stdlib"

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up default Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install build tools
        run: python -m pip install poetry==${{ env.POETRY_VERSION}}
      - name: Build package
        run: poetry build
      - name: Upload to PyPI
        run: poetry publish --username=__token__ --password=${{ secrets.PYPI_TOKEN }}
      - name: Generate requirements file for installer
        run: poetry export -n -o requirements-installer.txt -E installer
      - name: Generate requirements file for Heroku
        run: poetry export -n --without-hashes -o requirements-heroku.txt -E heroku
      - name: Add Kustosz to Heroku requirements
        run: echo "kustosz==${{github.ref_name}}" >> requirements-heroku.txt
      - uses: actions/upload-artifact@v3
        with:
          name: requirements.txt
          path: requirements-*.txt
  publish-github:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        id: download_requirements
        with:
          name: requirements.txt
      - name: Prepare GitHub release body
        run: |
          export previousTag=$(git tag --sort=-creatordate | sed -n 2p)
          echo '```' > "${{ env.CHANGELOG_PATH }}"
          git shortlog ${previousTag}..${{ github.ref }} >> "${{ env.CHANGELOG_PATH }}"
          echo '```' >> "${{ env.CHANGELOG_PATH }}"
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "${{ env.CHANGELOG_PATH }}"
          files: |
            ${{steps.download_requirements.outputs.download-path}}/requirements-installer.txt
            ${{steps.download_requirements.outputs.download-path}}/requirements-heroku.txt
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch frontend repository
        uses: actions/checkout@v3
        with:
          repository: "KustoszApp/web-ui"
          path: ".frontend"
          fetch-depth: 0
      - name: Checkout latest frontend tag
        run: |
          cd .frontend
          export previousTag=$(git tag --sort=-creatordate | head -n 1)
          git checkout "$previousTag"
      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/kustosz/app
          tags: "latest ${{ github.ref_name }}"
          platforms: linux/amd64, linux/arm64
          containerfiles: |
            ./Dockerfile
      - name: Push To quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: kustosz/app
          tags: ${{ steps.build-image.outputs.tags }}
          registry: quay.io/
          username: ${{ secrets.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_PASSWORD }}
