name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
env:
  NOX_VERSION: "2024.4.15"
  POETRY_VERSION: "1.8.2"
  # If it's good enough for nox, it's good enough for us
  FORCE_COLOR: "1"
  PRE_COMMIT_COLOR: "always"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up default Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install build tools
        run: python -m pip install nox==${{ env.NOX_VERSION}} poetry==${{ env.POETRY_VERSION}}
      - name: Actually lint
        run: nox --non-interactive --error-on-missing-interpreter --session "lint"
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install build tools
        run: python -m pip install nox==${{ env.NOX_VERSION}} poetry==${{ env.POETRY_VERSION}}
      - name: Actually test
        run: nox --non-interactive --error-on-missing-interpreter --session "tests-${{ matrix.python-version }}" -- --full-trace
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch frontend repository
        uses: actions/checkout@v3
        with:
          repository: "KustoszApp/web-ui"
          path: ".frontend"
          fetch-depth: 0
      - name: Build container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: quay.io/kustosz/app
          tags: "latest ${{ github.ref_name }}"
          platforms: linux/amd64
          containerfiles: |
            ./Dockerfile
